name: C Compile and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: gcc nr.c -o nr

      - name: Run
        run: ./nr
